name: CI

on:
  push:
  workflow_dispatch:

env:
  json: '{"key":"value"}'
  secret_json: ${{ secrets.SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test
        env:
          key: ${{ fromJSON(env.json).key }}
          fruit: ${{ fromJSON(env.json).fruit }}
          tree: ${{ fromJSON(env.json).tree }}
        run: |
          echo "key: $key"
          echo "fruit: $fruit"
          echo "tree: $tree"
